### PR TITLE
chore: migrate to cli-table3

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by davidchambers** [comment]
Why does the package name keep changing, @DanielRuf?

**Comment by DanielRuf** [comment]
> Why does the package name keep changing, @DanielRuf?

The change to `cli-table3`? Well, `cli-table2` is not actively maintained anymore, has open PRs and issues, vulnerabilities and so on so we created a fork to address all these things under a new org (where all have the needed rights).

**Comment by davidchambers** [comment]
Ah, I see. Such fragmentation is unfortunate.

@Avaq, shall we merge this?

**Comment by Avaq** [comment]
Sure! Thank you @DanielRuf.

**Review by Avaq — APPROVED** [review]

**Comment by davidchambers** [comment]
@Avaq, this failed CI due to the use of `const` and `let`. Shall we revert to the old package, or drop support for older Node versions?

**Comment by Avaq** [comment]
I don't think any officially supported Node versions that don't know `const` and `let` exist any more. It's probably okay to keep the change.

**Comment by DanielRuf** [comment]
Node.js 4 officially reached its EOL a few months ago. ;-)

**Comment by wuweiss** [comment]
Could someone please make a new release with the updated package. Thank you!

**Comment by Avaq** [comment]
> Could someone please make a new release with the updated package. Thank you!

@davidchambers Shall I do this?

**Comment by davidchambers** [comment]
That would be wonderful! Thank you, Aldwin. :)

**Comment by Avaq** [comment]
@wuweiss Done. :)

**Pull request merged**
